[build-system]

requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["promptopt*"]

[project]
dependencies = [
]
name = "promptopt"
version = "0.1.0"
authors = [
  { name="Oleh Kostromin", email="oleh@dataforce.solutions" },
]
description = ""
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "optuna>=4.7.0",
    "pytest>=9.0.2",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"
